apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-server-pv
spec:
  storageClassName: nfs-client
  capacity:
    storage: 100Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /hikvision
