# User volume configuration with an additional NVMe disk
apiVersion: v1alpha1
kind: UserVolumeConfig
name: cold-storage
provisioning:
  diskSelector:
    match: disk.dev_path == '/dev/sda'
  minSize: 480GB