apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgres-server-pv
spec:
  storageClassName: longhorn
  capacity:
    storage: 30Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: "/var/lib/postgresql/18/docker"