apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-server-pvc
  namespace: {{ .Values.namespace }}
spec:
  storageClassName: longhorn
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
  volumeName: postgres-server-pv