apiVersion: v2
name: base
description: Base chart for provisioning a k8s cluster
type: application
version: 0.1.0
appVersion: "1.16.0"

dependencies:
  - name: longhorn
    version: "1.12.1"
    repository: "https://charts.longhorn.io"
    condition: longhorn.enabled
